src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 * fields={"email"},
 * message= "email que vous avez indiqué est déjà utilisé !"
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min="8",minMessage="votre mot de passe doit faire minimum 8 caractères")
     */
    private $password;

    /**
     * @Assert\EqualTo(propertyPath="password", message="vous n\'avez pas tapez le meme mot de passe")
     */
    public $confirm_password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
    public function eraseCredentials() {}
    public function getSalt() {}
    public function getRoles() {
      return['ROLE_USER'];
    }

}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Component\HttpFoundation\Request;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Back\User;
use App\Form\RegistrationType;
use App\Form\ResetPasswordType;
use Symfony\Component\Security\Core\Encoder\BasePasswordEncoder;
use Symfony\Component\Security\Core\Exception\BadCredentialsException;
use Symfony\Component\Form\FormError;


class SecurityController extends AbstractController
{
  /**
   * @Route("/create-user", name="create-user")
   */
  public function registration(Request $request, ObjectManager $manager,UserPasswordEncoderInterface $encoder, \Swift_Mailer $mailer){
    $user = new User();
    $form= $this->createForm(RegistrationType::class,$user);
    $form->handleRequest($request);
      $random = openssl_random_pseudo_bytes(8);
      $random = bin2hex($random);


    if($form->issubmitted() && $form->isValid()) {
      $hash = $encoder->encodePassword($user,$random);
      $user->setPassword($hash);
      $manager->persist($user);
      $manager->flush();
      $task = $form->getData();

    $message = (new \Swift_Message('AssessBoard  Inscription'))
      ->setFrom('assessboard.sippe@gmail.com')
      ->setTo($form->get('email')->getData())
      // Or set it after like this
      ->setBody(
           $this->renderView(
              'mail/mail.html.twig',
              ['user' => $user,
              'password'=> $random]
          )
      );

      $mailer->send($message);

      return $this->redirectToRoute('security_login');
    }
      return $this->render('security/create-user.html.twig',[
          'form' => $form->createView()
      ]);
  }
    /**
     * @Route("/connexion", name="security_login")
     */
    public function login(){
        return $this->render('security/login.html.twig',[
        ]);
    }
    /**
     * @Route("/deconnexion", name="security_logout")
     */
    public function logout(){

    }



    /**
     * @Route("/edit_password", name="edit_password")
     *
     */
        public function editAction(Request $request,UserPasswordEncoderInterface $encoder)
            {

              $em = $this->getDoctrine()->getManager();
                 $user = $this->getUser();
             	$form = $this->createForm(ResetPasswordType::class, $user);

             	/*$form->handleRequest($request);
                 if ($form->isSubmitted() && $form->isValid()) {

                     //$passwordEncoder = $this->get('security.password_encoder');
                     dump($request->request);
                     die;
                     $oldPassword = $request->request->get('etiquettebundle_user')['oldPassword'];

                     // Si l'ancien mot de passe est bon
                     if ($encoder->isPasswordValid($user, $oldPassword)) {
                         $newEncodedPassword = $encoder->encodePassword($user, $user->getPlainPassword());
                         $user->setPassword($newEncodedPassword);

                         $em->persist($user);
                         $em->flush();

                         $this->addFlash('notice', 'Votre mot de passe à bien été changé !');

                         return $this->redirectToRoute('profile');
                     } else {
                         $form->addError(new FormError('Ancien mot de passe incorrect'));
                     }
                 }**/
                 if ($request->isMethod('POST')) {
                   DUMP($user);
                   die;
                 $newEncodedPassword = $encoder->encodePassword($user, $user->getPlainPassword());
                 $user->setPassword($newEncodedPassword);

                 $em->persist($user);
                 $em->flush();
 }
            return $this->render('security/edit.html.twig', array(
              'form' => $form->createView(),
            ));

}
}

templates/security/create-user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création d'utilisateur{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{asset('build/css/app.css')}}">
    <link rel="stylesheet" href="assets/css/back/create-survey.css">
{% endblock %}

{% block body %}
<div class="container">
  <div class="pb-2 mt-4 mb-5 border-bottom">
    <h1>Création d'utilisateur</h1>
  </div>
    <div class="card">
    <img class="card-img-top" src="assets/img/create_user_banner.jpg" alt="Card image cap" style= "max-height: 400px; width: auto;">
    <div class="card-body">
        {{ form_start(form)}}


        {#form_row(form.password,{'label': 'Mot de passe','attr': {'placeholder': 'Mot de passe'}}) #}
        {#form_row(form.confirm_password,{'label': 'Confirmation du Mot de passe','attr': {'placeholder': 'Répétez votre de passe'}}) #}

        <div class="form-group row justify-content-center">
            <label for="pseudo" class="col-sm-2 col-form-label">Nom d'utilisateur</label>
              <div class="col-sm-7">
                {{form_row(form.username,{'label': 'Nom d\'Utilisateur','attr': {'placeholder': 'Nom d\'utilisateur...'}}) }}
              </div>
        </div>
        <div class="form-group row justify-content-center">
            <label for="email" class="col-sm-2 col-form-label">Adresse email</label>
              <div class="col-sm-7">
                {{form_row(form.email,{'label': 'Adresse Email','attr': {'placeholder': 'Adresse Email...'}}) }}
              </div>
              <small id="emailHelpBlock" class="form-text text-muted">
                  Un email sera envoyé au nouvel utilisateur avec un mot de passe généré.
              </small>
        </div>
        <div class="form-group row justify-content-center">
          <label for="rank" class="col-sm-2 col-form-label">Type de compte</label>
            <div class="col-sm-7">
            {{ form_row(form.roles)}}
              <small id="rankHelpBlock" class="form-text text-muted">
                  Un simple utilisateur ne peut pas créer de questionnaire mais peut consulter les statistiques et réponses.
              </small>
          </div>
          <div class="w-100"></div>
        <div class="form-group row justify-content-center">
          <label class="col-sm-2 col-form-label"></label>
          <div class="col-sm-7">
            <button type="submit" class="btn btn-primary" id="Submit">Créer</button>
          </div>
        </div>

</div>
</div>
        {{ form_end(form)}}

</div>

{% block javascripts %}
    <script src="{{ asset('build/js/app.js') }}"> </script>
{% endblock %}
{% endblock %}

templates/security/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier mot de passe{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{asset('build/css/app.css')}}">
    <link rel="stylesheet" href="assets/css/front/signinn.css">
{% endblock %}

{% block body %}
<br>
<br>
<br>
{% form_theme form 'bootstrap_4_layout.html.twig' %}
<form action="{{ path('security_login') }}">
  {{ form_start(form)}}


  {{ form_end(form)}}
</form>


{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Login{% endblock %}
{% block stylesheets %}
    <link rel="stylesheet" href="{{asset('build/css/app.css')}}">
    <link rel="stylesheet" href="assets/css/front/login.css">

{% endblock %}

{% block body %}

<div class="auth">
  <div class="auth__form">
    <div class="login-form">
      <form action="{{ path('security_login') }}" method="post">
          <h2 class="text-center">Login</h2>
          <div class="form-group">
              <input type="text" name="_username" class="form-control" placeholder="Username" required="required">
          </div>
          <div class="form-group">
              <input type="password" name="_password" class="form-control" placeholder="Password" required="required">
          </div>
          <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block">LOGIN</button>
          </div>
          <div class="clearfix">
              <label class="pull-left checkbox-inline"><input type="checkbox"> Remember me</label>
          </div>
          <div class="forgot">
            <a href="#" class=" out_link pull-right">Forgot Password?</a>
          </div>
      </form>
    </div>
  </div>
{% endblock %}